### ISSUE TITLE
[Bug Report]Q cannot be reshaped correctly when model is loaded in 4bit

### ISSUE THREAD

**Issue by po13on** [hannamw/eap-ig-faithfulness#1]
**code example：**
```python
model = AutoModelForCausalLM.from_pretrained(model_name, cache_dir=cache_dir, proxies=proxies,local_files_only=False, low_cpu_mem_usage=True, use_safetensors=False, load_in_4bit=True, torch_dtype=torch.float32, )
tokenizer = AutoTokenizer.from_pretrained(model_name)
model_hooked = transformer_lens.HookedTransformer.from_pretrained("unsloth/mistral-7b-instruct-v0.2-bnb-4bit",hf_model=model_merged, hf_model_4bit=True, fold_ln=False, fold_value_biases=False, center_writing_weights=False, center_unembed=False, tokenizer=tokenizer)
task = 'ioi'
model.cfg.use_split_qkv_input = True
model.cfg.use_attn_result = True
model.cfg.use_hook_mlp_in = True
task_metric_name = 'logit_diff'
ds = EAPDataset(task, model_name)
ds.head(3000)
batch_size = 20
dataloader = ds.to_dataloader(batch_size)
task_metric = get_metric(task_metric_name, task, model=model)
g = Graph.from_model(model)
attribute(model, g, dataloader, partial(task_metric, mean=True, loss=True), integrated_gradients=5)
```

**error:**
```python
File ~/python_library/TransformerLens/transformer_lens/components/abstract_attention.py:364, in AbstractAttention.calculate_qkv_matrices(self, query_input, key_input, value_input)
    339        if self.cfg.load_in_4bit:
    340            q = self.hook_q(
    341                # call bitsandbytes method to dequantize and multiply
    342                bnb.matmul_4bit(
    343                    query_input,
    344                    self.W_Q.t(),
    345                    bias=None,
    346                    quant_state=self.W_Q.quant_state,
-->347                ).reshape(
    348                    query_input.shape[0],
    349                    query_input.shape[1],
    350                    self.cfg.n_heads,
    351                    self.cfg.d_head,
    352                )
    353                + self.b_Q
RuntimeError: shape '[20, 22, 32, 128]' is invalid for input of size 57671680"
```

**Describe the bug**
query_input's size is [batch, pos, n_heads, d_model], and the purpose of the code where the error occurred is to reshape query_input to [batch, pos, n_heads, d_head]. 
I found that the size of output of bnb.matmul_4bit is still [batch, pos, n_heads, d_model] so it cannot be reshaped to [batch, pos, n_heads, d_head].

The reason for this error may be the following code in transformer_lens：
```python
if self.cfg.load_in_4bit:
     nq = int((self.cfg.d_model * self.cfg.d_head * self.cfg.n_heads) / 2)
     self.W_Q = Params4bit(torch.empty(nq, 1, dtype=torch.uint8), requires_grad=False)
     self.W_O = Params4bit(torch.empty(nq, 1, dtype=torch.uint8), requires_grad=False)
```
The shape of matrix W_Q is [(self.cfg.d_model * self.cfg.d_head * self.cfg.n_heads) / 2, 1], which leads to the unexpected shape of the output from the bnb.matmul_4bit function.

**Comment by hannamw** [comment]
Hi—thanks for using this library and for making a bug report! 

Is that the full stacktrace? It looks to me like the bug comes entirely from the `HookedTransformer.from_pretrained` method, probably because TransformerLens only supports quantization with Llama; see [this issue](https://github.com/TransformerLensOrg/TransformerLens/issues/684) from someone else who wanted to work with the same model. So, I think the issue is on their side, not mine. 

That said, I wouldn't recommend using this code with quantized models; it's not built for that. Also, this repo focuses primarily on reproducing experiments from the associated paper; if you want to find circuits, you're better off using the submodule [here](https://github.com/hannamw/eap-ig).

**Comment by po13on** [comment]
Thanks for your comment. I now know the cause of this bug. When I load the model in 4-bit and set model.cfg.use_split_qkv_input = True, this bug will be triggered. So could you tell me if model.cfg.use_stlit_qkv_input can be set to false？

**Comment by hannamw** [comment]
Sorry to have missed this—no, right now, this repo expects q/k/v to be split, as it considers the computational graph involve edges  to each attention head's q/k/v inputs separately. You could rewrite things to consider all of the attention head inputs together (so ablations would change all of q/k/v at once), but I'm not sure I'd recommend that.
